out:sort.c main.o show.o mod.o add.o read.o save.o del.o
	cc sort.c main.c show.c mod.c add.c read.c save.c del.c
sort.o:sort.c
	cc -c sort.c
main.o:main.c
	cc -c main.c
show.o:show.c
	cc -c show.c
mod.o:mod.c
	cc -c mod.c
add.o:add.c
	cc -c add.c
read.o:read.c
	cc -c read.c
save.o:save.c
	cc -c save.c
del.o:del.c
	cc -c del.c
clean:
	rm -f out *.o


